# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 603)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.ui_add_measure_btn = QtWidgets.QPushButton(self.centralWidget)
        self.ui_add_measure_btn.setGeometry(QtCore.QRect(12, 39, 114, 32))
        self.ui_add_measure_btn.setObjectName("ui_add_measure_btn")
        self.ui_tab_tbl = QtWidgets.QTableView(self.centralWidget)
        self.ui_tab_tbl.setGeometry(QtCore.QRect(134, 43, 469, 469))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ui_tab_tbl.sizePolicy().hasHeightForWidth())
        self.ui_tab_tbl.setSizePolicy(sizePolicy)
        self.ui_tab_tbl.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ui_tab_tbl.setObjectName("ui_tab_tbl")
        self.ui_save_btn = QtWidgets.QPushButton(self.centralWidget)
        self.ui_save_btn.setGeometry(QtCore.QRect(10, 120, 114, 32))
        self.ui_save_btn.setObjectName("ui_save_btn")
        self.ui_load_btn = QtWidgets.QPushButton(self.centralWidget)
        self.ui_load_btn.setGeometry(QtCore.QRect(10, 80, 114, 32))
        self.ui_load_btn.setObjectName("ui_load_btn")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 251, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ui_add_measure_btn.setText(_translate("MainWindow", "Add Measure"))
        self.ui_save_btn.setText(_translate("MainWindow", "Save"))
        self.ui_load_btn.setText(_translate("MainWindow", "Load File"))
        self.label.setText(_translate("MainWindow", "Kalimba Tab Generator"))
